### ISSUE TITLE
Readme.md

### ISSUE THREAD

**Issue by ghost** [aldonline/node-sparql#1]
Please, Do add in the Readme.MD, for the dummies like me, the following:

```
If you want to make insertions through the sparql endpoints, make sure that you have the permission to do that:

Use isql: 

SQL> grant execute on DB.DBA.SPARQL_MODIFY_BY_DICT_CONTENTS to "SPARQL"; 
```

**Comment by aldonline** [comment]
Good idea!
Why don't u add it yourself?
Use git fork ;)
and then issue a "pull request".

On Jul 3, 2011, at 2:30,
hermanjungereply@reply.github.com
wrote:
